
class Organization(object):

    def __init__(self):

    @property
    def division(self):
        return random.choice([
            'Marketing',
            'Human Resources',
            'Information Security',
            'Accounting',
            'Payroll',
            'Engineering',
            'Project Management',
            'Vice President',
            'Office of the CISO',
            'IT Operations'
        ])

    @property
    def title(self):
        return random.choice([
            "Actor",
            "Administrator",
            "Aeronautical engineer",
            "Air traffic controller",
            "Airline pilot",
            "Animal technologist",
            "Animator",
            "Applications developer",
            "Architect",
            "Architectural technologist",
            "Archivist",
            "Armed forces logistics/support/administrative officer",
            "Armed forces operational officer",
            "Armed forces technical officer",
            "Armed forces training and education officer",
            "Associate Professor",
            "Astronomer",
            "Audiological scientist",
            "Automotive engineer",
            "Brewing technologist",
            "Broadcast engineer",
            "Careers information officer",
            "Cartographer",
            "Chief Executive Officer",
            "Chief Financial Officer",
            "Chief Marketing Officer",
            "Chief of Staff",
            "Chief Operating Officer",
            "Chief Strategy Officer",
            "Chief Technology Officer",
            "Child psychotherapist",
            "Data scientist",
            "Database administrator",
            "Electrical engineer",
            "Electronics engineer",
            "Engineer, communications",
            "Engineer, electronics",
            "Engineer, technical sales",
            "Forensic scientist",
            "Human resources officer",
            "Information systems manager",
            "Intelligence analyst",
            "IT consultant",
            "IT sales professional",
            "IT technical support officer",
            "IT trainer",
            "Lawyer",
            "Market researcher",
            "Marketing executive",
            "Multimedia programmer",
            "Network engineer",
            "Office manager",
            "Operational researcher",
            "Patent attorney",
            "Police officer",
            "Research officer, government",
            "Research officer, political party",
            "Research officer, trade union",
            "Risk analyst",
            "Risk manager",
            "Sales executive",
            "Sales professional, IT",
            "Scientist, forensic",
            "Senior tax professional/tax inspector",
            "Social research officer, government",
            "Social researcher",
            "Software engineer",
            "Technical author",
            "Technical sales engineer",
            "Video editor",
            "Web designer",
            "Writer"
        ])

