from .baseclass import BaseClass


class Organization(BaseClass):
    """The Organization class contains information related to organizations
    """

    _name = None

    @property
    def name(self):
        """A randomly generated organization name

        Returns:
            str: A randomly generated organization name
        """
        if not self._name:
            first = self.random.choice([
                'Adaptive',
                'Advanced',
                'Ameliorated',
                'Assimilated',
                'Automated',
                'Balanced',
                'Business-focused',
                'Centralized',
                'Cloned',
                'Compatible',
                'Configurable',
                'Cross-group',
                'Cross-platform',
                'Customer-focused',
                'Customizable',
                'Decentralized',
                'De-engineered',
                'Devolved',
                'Digitized',
                'Distributed',
                'Diverse',
                'Down-sized',
                'Enhanced',
                'Enterprise-wide',
                'Ergonomic',
                'Exclusive',
                'Expanded',
                'Extended',
                'Face-to-face',
                'Focused',
                'Front-line',
                'Fully-configurable',
                'Function-based',
                'Fundamental',
                'Future-proofed',
                'Grass-roots',
                'Horizontal',
                'Implemented',
                'Innovative',
                'Integrated',
                'Intuitive',
                'Inverse',
                'Managed',
                'Mandatory',
                'Monitored',
                'Multi-channeled',
                'Multi-lateral',
                'Multi-layered',
                'Multi-tiered',
                'Networked',
                'Object-based',
                'Open-architected',
                'Open-source',
                'Operative',
                'Optimized',
                'Optional',
                'Organic',
                'Organized',
                'Persevering',
                'Persistent',
                'Phased',
                'Polarized',
                'Pre-emptive',
                'Proactive',
                'Profit-focused',
                'Profound',
                'Programmable',
                'Progressive',
                'Public-key',
                'Quality-focused',
                'Reactive',
                'Realigned',
                'Re-contextualized',
                'Re-engineered',
                'Reduced',
                'Reverse-engineered',
                'Right-sized',
                'Robust',
                'Seamless',
                'Secured',
                'Self-enabling',
                'Sharable',
                'Stand-alone',
                'Streamlined',
                'Switchable',
                'Synchronized',
                'Synergistic',
                'Synergized',
                'Team-oriented',
                'Total',
                'Triple-buffered',
                'Universal',
                'Up-sized',
                'Upgradable',
                'User-centric',
                'User-friendly',
                'Versatile',
                'Virtual',
                'Visionary',
                'Vision-oriented'
            ])

            second = self.random.choice([
                'ability',
                'access',
                'adapter',
                'algorithm',
                'alliance',
                'analyzer',
                'application',
                'approach',
                'architecture',
                'archive',
                'artificial intelligence',
                'array',
                'attitude',
                'benchmark',
                'budgetary management',
                'capability',
                'capacity',
                'challenge',
                'circuit',
                'collaboration',
                'complexity',
                'concept',
                'conglomeration',
                'contingency',
                'core',
                'customer loyalty',
                'database',
                'data-warehouse',
                'definition',
                'emulation',
                'encoding',
                'encryption',
                'extranet',
                'firmware',
                'flexibility',
                'focus group',
                'forecast',
                'frame',
                'framework',
                'function',
                'functionalities',
                'Graphic Interface',
                'groupware',
                'Graphical User Interface',
                'hardware',
                'help-desk',
                'hierarchy',
                'hub',
                'implementation',
                'info-mediaries',
                'infrastructure',
                'initiative',
                'installation',
                'instruction set',
                'interface',
                'Internet solution',
                'intranet',
                'knowledge user',
                'knowledgebase',
                'Local Area Network',
                'leverage',
                'matrices',
                'matrix',
                'methodology',
                'middleware',
                'migration',
                'model',
                'moderator',
                'monitoring',
                'moratorium',
                'neural-net',
                'open architecture',
                'open system',
                'orchestration',
                'paradigm',
                'parallelism',
                'policy',
                'portal',
                'pricing structure',
                'process improvement',
                'product',
                'productivity',
                'project',
                'projection',
                'protocol',
                'secured line',
                'service-desk',
                'software',
                'solution',
                'standardization',
                'strategy',
                'structure',
                'success',
                'superstructure',
                'support',
                'synergy',
                'system engine',
                'task-force',
                'throughput',
                'time-frame',
                'toolset',
                'utilization',
                'website',
                'workforce'
            ])
            self._name = "{} {}".format(first.capitalize(), second.capitalize())
        return self._name

    @property
    def domain(self):
        """Returns a domain name based on the organization name

        Returns:
            str: Returns a domain name based on the organizational name
        """
        return self.name.split(' ')[0].upper()
            
    @property
    def division(self):
        """Returns a division within an organization

        Returns:
            str: Returns a division within an organization
        """
        return self.random.choice([
            'Marketing',
            'Human Resources',
            'Information Security',
            'Accounting',
            'Payroll',
            'Engineering',
            'Project Management',
            'Vice President',
            'Office of the CISO',
            'IT Operations'
        ])

    @property
    def title(self):
        """Returns a title within an organization

        Returns:
            str: Returns a title within an organization
        """
        return self.random.choice([
            "Actor",
            "Administrator",
            "Aeronautical engineer",
            "Air traffic controller",
            "Airline pilot",
            "Animal technologist",
            "Animator",
            "Applications developer",
            "Architect",
            "Architectural technologist",
            "Archivist",
            "Armed forces logistics/support/administrative officer",
            "Armed forces operational officer",
            "Armed forces technical officer",
            "Armed forces training and education officer",
            "Associate Professor",
            "Astronomer",
            "Audiological scientist",
            "Automotive engineer",
            "Brewing technologist",
            "Broadcast engineer",
            "Careers information officer",
            "Cartographer",
            "Chief Executive Officer",
            "Chief Financial Officer",
            "Chief Marketing Officer",
            "Chief of Staff",
            "Chief Operating Officer",
            "Chief Strategy Officer",
            "Chief Technology Officer",
            "Child psychotherapist",
            "Data scientist",
            "Database administrator",
            "Electrical engineer",
            "Electronics engineer",
            "Engineer, communications",
            "Engineer, electronics",
            "Engineer, technical sales",
            "Forensic scientist",
            "Human resources officer",
            "Information systems manager",
            "Intelligence analyst",
            "IT consultant",
            "IT sales professional",
            "IT technical support officer",
            "IT trainer",
            "Lawyer",
            "Market researcher",
            "Marketing executive",
            "Multimedia programmer",
            "Network engineer",
            "Office manager",
            "Operational researcher",
            "Patent attorney",
            "Police officer",
            "Research officer, government",
            "Research officer, political party",
            "Research officer, trade union",
            "Risk analyst",
            "Risk manager",
            "Sales executive",
            "Sales professional, IT",
            "Scientist, forensic",
            "Senior tax professional/tax inspector",
            "Social research officer, government",
            "Social researcher",
            "Software engineer",
            "Technical author",
            "Technical sales engineer",
            "Video editor",
            "Web designer",
            "Writer"
        ])
